##############################################################################
# environments/uat.tfvars — Variable values for the UAT environment
#
# Resources Terraform will create:
#   rg-cashflow-tf-uat
#   asp-cashflow-tf-uat
#   cashflowapi-akash2026-uat
#   cashflowweb-akash2026-uat
#   cashflowdb-akash2026-uat  (Cosmos DB for MongoDB)
##############################################################################

environment             = "uat"
location                = "centralindia"
static_web_app_location = "eastasia"

project       = "cashflow"
unique_suffix = "akash2026"

app_service_sku = "B1"
node_runtime    = "NODE:20-lts"
client_url      = "https://uat.cash-flow.in"
api_base_url    = "https://api-uat.cash-flow.in"

# ── Secrets — set via TF_VAR_* environment variables ─────────────────────────
# cosmosdb_admin_password is NOT needed — auto-generated by random_password
#   resource and stored securely in Terraform state. Retrieve it with:
#   terraform output -raw cosmosdb_connection_string
# jwt_secret  = set via: $env:TF_VAR_jwt_secret = "different-secret-for-uat"

jwt_access_expiry  = "6h"
jwt_refresh_expiry = "14d"
bcrypt_rounds      = 10
rate_limit_ttl     = 60
rate_limit_max     = 100

google_client_id     = ""
google_client_secret = ""
github_client_id     = ""
github_client_secret = ""
